version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile

    image: bankend
    ports:
      - "8080:8080"

    networks:
      - postgres-net



networks:
  postgres-net:
    external: true